name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  selective:
    runs-on: ubuntu-latest
    name: Selective
    strategy:
      fail-fast: false
      matrix:
        ci_node_total: [4]
        ci_node_index: [0, 1, 2, 3]
    env:
      SELECTIVE_HOST: wss://staging.selective.ci

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Setup Selective
        uses: selectiveci/setup-selective@v1
        with:
          api-key: ${{ secrets.SELECTIVE_API_KEY }}
          runner-id: ${{ matrix.ci_node_index }}

      - name: Run the default task
        run: bundle exec selective rspec --log

      - name: Store logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: ./log/*.log
